default_python_exec: python
pid_file: watcher_archivers_test2.pid
polling_time: 60


processes:
  archivers:
    script: /home/nicolas/thesis/rmq-zmq/archiver.py
    instances:
      - '-v thesis -rk routing_key.example -s thesis -posto plain'
      - '-v thesis -rk routing_key.example -s thesis -posto plain'
      - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
      # - '-v thesis -rk routing_key.example -s thesis -posto plain'
