messages:
  profiler:
    client_send_ts: TIMESTAMP  # request sent
    loanServicePT_ts: TIMESTAMP
    loanServiceReplyPT_ts: TIMESTAMP
    cleint_received_ts: TIMESTAMP  # response received

  creditInformationMessage:
    firstName: STRING
    name: STRING
    amount: AMOUNT_INTEGER
    info: profiler

  approvalMessage:
    accept: ACCEPT_STRING
    info: profiler

  riskAssessmentMessage:
    level: RISK_STRING
    info: profiler

  errorMessage:
    errorCode: ERROR_INTEGER
    info: profiler
